# Generated by Django 5.1.7 on 2025-03-23 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_job_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='nice_to_have',
            field=models.TextField(blank=True, null=True),
        ),
    ]
