# Generated by Django 5.1.7 on 2025-03-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cities',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='authentication.city'),
        ),
    ]
