# Generated by Django 5.1.7 on 2025-03-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_job_cities'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolishCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('voivodeship', models.CharField(blank=True, max_length=100, null=True)),
                ('population', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Polish cities',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='job',
            name='cities',
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
