# Generated by Django 5.1.7 on 2025-03-26 20:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_polishcity_remove_job_cities_delete_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-posted_date'], 'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
        migrations.AlterModelOptions(
            name='polishcity',
            options={'ordering': ['name'], 'verbose_name': 'Polish City', 'verbose_name_plural': 'Polish Cities'},
        ),
        migrations.AddField(
            model_name='polishcity',
            name='name_pl',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Polish Name'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(max_length=255, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Company Logo'),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Featured'),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_remote',
            field=models.BooleanField(default=False, verbose_name='Remote'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_url',
            field=models.URLField(blank=True, null=True, verbose_name='Job URL'),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='job',
            name='nice_to_have',
            field=models.TextField(blank=True, null=True, verbose_name='Nice to Have'),
        ),
        migrations.AlterField(
            model_name='job',
            name='posted_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Posted Date'),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.TextField(blank=True, null=True, verbose_name='Requirements'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Salary'),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Temporary', 'Temporary')], default='Full-time', max_length=50, verbose_name='Job Type'),
        ),
        migrations.AlterField(
            model_name='polishcity',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='polishcity',
            name='population',
            field=models.IntegerField(blank=True, null=True, verbose_name='Population'),
        ),
        migrations.AlterField(
            model_name='polishcity',
            name='voivodeship',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Voivodeship'),
        ),
    ]
