# Generated by Django 5.1.7 on 2025-04-02 17:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_customuser_company_name_customuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('interviewing', 'Interviewing'), ('offer', 'Received Offer'), ('rejected', 'Rejected'), ('accepted', 'Accepted Offer'), ('declined', 'Declined Offer')], default='applied', max_length=20, verbose_name='Status')),
                ('applied_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Applied Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('employer_viewed', models.BooleanField(default=False, verbose_name='Employer Viewed')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='authentication.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-applied_date'],
                'unique_together': {('user', 'job')},
            },
        ),
    ]
